# Generated by Django 3.2 on 2022-09-13 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0008_tour_choose_location_tour_choose_multiple_locations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=32)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('product_total', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('total_discount', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('grand_total', models.DecimalField(decimal_places=6, default=0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_guests', models.IntegerField(default=0)),
                ('date_of_trip_or_event', models.DateField()),
                ('tour_discount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tour_total', models.DecimalField(decimal_places=2, editable=False, max_digits=6)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitems', to='checkout.order')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.tour')),
            ],
        ),
    ]
