# Generated by Django 3.2 on 2022-09-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='date_of_trip_or_event',
            field=models.CharField(max_length=100),
        ),
    ]
