# Generated by Django 4.0 on 2022-08-31 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='itinerary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
