# Generated by Django 4.0 on 2022-08-31 17:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_tour_itinerary'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='accomodation',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AddField(
            model_name='tour',
            name='max_num_of_guests',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='tour',
            name='num_of_breakfast',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AddField(
            model_name='tour',
            name='num_of_dinner',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AddField(
            model_name='tour',
            name='transport',
            field=models.CharField(blank=True, choices=[('Bus', 'Bus'), ('Ferry', 'Ferry'), ('Train', 'Train'), ('Bus and Ferry', 'Bus and Ferry'), ('Bus and Train', 'Bus and Train'), ('Train and Ferry', 'Train and Ferry')], max_length=30, null=True),
        ),
    ]
