# Generated by Django 4.0 on 2022-08-31 18:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_tour_accomodation_tour_max_num_of_guests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='max_num_of_guests',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='tour',
            name='transport',
            field=models.CharField(choices=[('Bus', 'Bus'), ('Ferry', 'Ferry'), ('Train', 'Train'), ('Bus and Ferry', 'Bus and Ferry'), ('Bus and Train', 'Bus and Train'), ('Train and Ferry', 'Train and Ferry')], default=0, max_length=30),
        ),
    ]
