# Generated by Django 4.0 on 2022-09-02 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='dates',
            field=models.ManyToManyField(related_name='Date', to='products.Date'),
        ),
    ]
