# Generated by Django 4.0 on 2022-09-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_date_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='choose_location',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='choose_multiple_locations',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
